# Generated by Django 5.2 on 2025-04-13 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='coverText',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='apply/'),
        ),
        migrations.AddField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='job.job'),
        ),
        migrations.AddField(
            model_name='apply',
            name='websit',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
