# Generated by Django 5.2 on 2025-04-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_apply_created_at_alter_apply_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='websit',
            new_name='website',
        ),
    ]
